// Date: 05/08/2013 22:58:44
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package shadowhax.crystalluscraft.block.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCrystalStage4 extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
  
  public ModelCrystalStage4()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(-1F, 0F, -3F, 5, 1, 5);
      Shape1.setRotationPoint(-2F, 23F, 1F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 22);
      Shape2.addBox(0F, 0F, 0F, 1, 5, 1);
      Shape2.setRotationPoint(-1F, 24F, -1F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, -0.5576792F, 0.2602503F, 2.974289F);
      Shape3 = new ModelRenderer(this, 4, 22);
      Shape3.addBox(0F, 0F, 0F, 1, 6, 1);
      Shape3.setRotationPoint(0F, 23F, 1F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0.8179294F, -0.1858931F, 3.141593F);
      Shape4 = new ModelRenderer(this, 8, 22);
      Shape4.addBox(0F, 0F, 0F, 1, 4, 1);
      Shape4.setRotationPoint(0F, 24F, 0F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, -1.07818F, -0.1487144F, 2.974289F);
      Shape5 = new ModelRenderer(this, 12, 22);
      Shape5.addBox(0F, 0F, 0F, 1, 4, 1);
      Shape5.setRotationPoint(-2F, 24F, 1F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, -0.8922867F, 1.784573F, 2.639681F);
      Shape6 = new ModelRenderer(this, 16, 22);
      Shape6.addBox(0F, 0F, 0F, 4, 1, 1);
      Shape6.setRotationPoint(-2F, 19F, 0F);
      Shape6.setTextureSize(64, 32);
      Shape6.mirror = true;
      setRotation(Shape6, -1.561502F, -1.375609F, -2.193538F);
      Shape7 = new ModelRenderer(this, 0, 18);
      Shape7.addBox(0F, 0F, 0F, 5, 2, 2);
      Shape7.setRotationPoint(-2F, 24F, -1F);
      Shape7.setTextureSize(64, 32);
      Shape7.mirror = true;
      setRotation(Shape7, 0.0743572F, -0.1115358F, -2.269341F);
      Shape8 = new ModelRenderer(this, 14, 18);
      Shape8.addBox(0F, 0F, 0F, 7, 2, 2);
      Shape8.setRotationPoint(0F, 23F, 0F);
      Shape8.setTextureSize(64, 32);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, -0.910876F);
      Shape9 = new ModelRenderer(this, 32, 15);
      Shape9.addBox(0F, 0F, 0F, 2, 5, 2);
      Shape9.setRotationPoint(0F, 24F, -1F);
      Shape9.setTextureSize(64, 32);
      Shape9.mirror = true;
      setRotation(Shape9, 0.0743572F, 1.264073F, -2.453788F);
      Shape10 = new ModelRenderer(this, 40, 17);
      Shape10.addBox(0F, 0F, -2F, 2, 3, 2);
      Shape10.setRotationPoint(2F, 24F, 2F);
      Shape10.setTextureSize(64, 32);
      Shape10.mirror = true;
      setRotation(Shape10, 0.8551081F, 0.4461433F, 3.141593F);
      Shape11 = new ModelRenderer(this, 48, 17);
      Shape11.addBox(0F, 0F, 0F, 2, 3, 2);
      Shape11.setRotationPoint(0F, 19F, 1F);
      Shape11.setTextureSize(64, 32);
      Shape11.mirror = true;
      setRotation(Shape11, 0.8551081F, -0.669215F, 3.141593F);
      Shape12 = new ModelRenderer(this, 0, 6);
      Shape12.addBox(0F, 0F, 0F, 3, 9, 3);
      Shape12.setRotationPoint(1F, 24F, -1.5F);
      Shape12.setTextureSize(64, 32);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0.2602503F, 3.067235F);
      Shape13 = new ModelRenderer(this, 12, 6);
      Shape13.addBox(0F, 0F, 0F, 2, 1, 2);
      Shape13.setRotationPoint(-0.2F, 15F, -0.7F);
      Shape13.setTextureSize(64, 32);
      Shape13.mirror = true;
      setRotation(Shape13, 0F, 0.260246F, 3.067242F);
      Shape14 = new ModelRenderer(this, 12, 9);
      Shape14.addBox(0F, 0F, 0F, 1, 1, 1);
      Shape14.setRotationPoint(-0.7F, 14F, -0.1F);
      Shape14.setTextureSize(64, 32);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0.260246F, 3.067242F);
  }
  
  public void render(float f)
  {
    Shape1.render(f);
    Shape2.render(f);
    Shape3.render(f);
    Shape4.render(f);
    Shape5.render(f);
    Shape6.render(f);
    Shape7.render(f);
    Shape8.render(f);
    Shape9.render(f);
    Shape10.render(f);
    Shape11.render(f);
    Shape12.render(f);
    Shape13.render(f);
    Shape14.render(f);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
