package shadowhax.crystalluscraft;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.network.NetworkRegistry;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.ItemStack;
import shadowhax.crystalluscraft.block.Blocks;
import shadowhax.crystalluscraft.core.handler.GuiHandler;
import shadowhax.crystalluscraft.core.proxy.ClientProxy;
import shadowhax.crystalluscraft.core.proxy.CommonProxy;
import shadowhax.crystalluscraft.core.util.Config;
import shadowhax.crystalluscraft.core.util.CrystallusCraftRegistry;
import shadowhax.crystalluscraft.core.util.Reference;
import shadowhax.crystalluscraft.item.Items;

import java.util.Arrays;

@Mod(modid = Reference.MOD_ID, name = Reference.MOD_NAME, version = Reference.MOD_VERSION)
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class CrystallusCraft {
	
	@SidedProxy(serverSide= Reference.SERVER_PROXY, clientSide= Reference.CLIENT_PROXY)
	public static CommonProxy proxy;

	@Mod.Instance(Reference.MOD_ID)
	public static CrystallusCraft instance;
	
	public static CreativeTabs tab = new CreativeTabCustom();

    public static int crystalRenderID;
	
	@Mod.EventHandler
	public void preInit(FMLPreInitializationEvent evt) {
		Config.createConfig(evt);
		getModMeta(evt.getModMetadata());
		
		Blocks.init();
		Items.init();
		ClientProxy.render();

        NetworkRegistry.instance().registerGuiHandler(instance, new GuiHandler());

        CrystallusCraftRegistry.addShapedRecipe(new ItemStack(Items.refinedCrystal, 3, 1),
            " xx  ",
            " xx  ",
            " xxx ",
            "  xx ",
            "  xx ",
            'x', new ItemStack(Items.rawCrystal, 1, 1)
        );
	}
	
	@Mod.EventHandler
	public void init(FMLInitializationEvent evt) {

	}
	
	@Mod.EventHandler
	public void postInit(FMLPostInitializationEvent evt) {
		
	}
	
	private void getModMeta(ModMetadata meta) {
		
		meta.authorList = Arrays.asList("Darkhax", "ShadowChild", "ThisGuy1045");
		meta.logoFile = "null";
		meta.autogenerated = false;
		meta.credits = "Coded by Darkhax and ShadowChild. Textures by ThisGuy1045";
		meta.description = "Don't want to give away the idea right now ;p";
		meta.url = "https://github.com/ShadowChild/ModJam";
	}
}