package shadowhax.modjam;

import java.util.Arrays;

import net.minecraft.block.Block;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.common.MinecraftForge;
import shadowhax.modjam.block.Blocks;
import shadowhax.modjam.core.proxy.ClientProxy;
import shadowhax.modjam.core.proxy.CommonProxy;
import shadowhax.modjam.core.util.Config;
import shadowhax.modjam.core.util.Reference;
import shadowhax.modjam.item.Items;
import shadowhax.modjam.recipe.RefinedRecipeManager;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;
import cpw.mods.fml.common.network.NetworkRegistry;
import cpw.mods.fml.common.registry.GameRegistry;

@Mod(modid = Reference.MOD_ID, name = Reference.MOD_NAME, version = Reference.MOD_VERSION)
@NetworkMod(clientSideRequired = true, serverSideRequired = false)
public class ModJam {
	
	@SidedProxy(serverSide= Reference.SERVER_PROXY, clientSide= Reference.CLIENT_PROXY)
	public static CommonProxy proxy;

	@Mod.Instance(Reference.MOD_ID)
	public static ModJam instance;
	
	public static CreativeTabs tab = new CreativeTabCustom();
	
	@Mod.EventHandler
	public void preInit(FMLPreInitializationEvent evt) {
		Config.createConfig(evt);
		getModMeta(evt.getModMetadata());
		
		new ShadowTest();
		Blocks.init();
		Items.init();
		ClientProxy.render();
		
		NetworkRegistry.instance().registerGuiHandler(this.instance,new shadowhax.modjam.core.handler.GuiHandler());	
	}
	
	@Mod.EventHandler
	public void init(FMLInitializationEvent evt) {
			
	}
	
	@Mod.EventHandler
	public void postInit(FMLPostInitializationEvent evt) {
		
	}
	
	private void getModMeta(ModMetadata meta) {
		
		meta.authorList = Arrays.asList(new String[] {"Darkhax", "ShadowChild", "ThisGuy1045"});
		meta.logoFile = "null";
		meta.autogenerated = false;
		meta.credits = "Coded by Darkhax and ShadowChild. Textures by ThisGuy1045";
		meta.description = "Don't want to give away the idea right now ;p";
		meta.url = "https://github.com/ShadowChild/ModJam";
	}
}
